### PR TITLE
Update GuiBook

### PR DESCRIPTION
**Pull request by AlphaWolf21**
Texture for background GUI needed, text and or images for the GUI needed, up to you to choose which one you would like to go with

### CODE REVIEW

**Comment by KillBait** [comment]
I can try and find some textures to use for the book,  I'm utterly terrible at art,  have opened a enhancement post  on issue tracker to make things a bit easier. 

I have actually started a complete rewrite of the mod,  old code wasnt flexible enough,  if we keep book code contained in separate classes will be easy to integrate into new mod

**Comment by AlphaWolf21** [comment]
any news on when you will finish the re write?

**Comment by KillBait** [comment]
still working on it, made some progress, got a little sidetracked by real life i'm afraid.

I plan on adding in a few basic machines this time, like essence based furnace and such, but 
that means networking code (totally not my area, so learning stuff as i go along)

I ploan to upload the source here once i get the base stuff working, hopefully shouldn't take to long

**Comment by AlphaWolf21** [comment]
Im not that bad when it comes to GUI's and Containers and such, but when it comes down to making my own recipe handler and linking that to the TE thats the part i dont know how to do

**Pull request merged**
